apiVersion: v1
kind: Service
metadata:
  name: machine-{{ .Values.machine.name | lower | replace " " "-" }}-svc
  namespace: xts-system
  labels:
    app: machine-{{ .Values.machine.name | lower | replace " " "-" }}
spec:
  selector:
    app: machine-{{ .Values.machine.name | lower | replace " " "-" }}
  ports:
    - name: rest
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.servicePort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
    - name: hmi
      port: {{ .Values.service.hmiPort }}
      targetPort: {{ .Values.service.hmiPort }}
  type: ClusterIP
