apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: xts-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prime-mover-service'
        static_configs:
          - targets: ['prime-mover-svc:8080']

      - job_name: 'prime-mover-api'
        static_configs:
          - targets: ['prime-mover-svc:8082']

      - job_name: 'machine-laser-welding'
        static_configs:
          - targets: ['machine-laserwelding-svc:8080']

      - job_name: 'machine-precision-assembly'
        static_configs:
          - targets: ['machine-precisionassembly-svc:8080']

      - job_name: 'machine-quality-inspection'
        static_configs:
          - targets: ['machine-qualityinspection-svc:8080']

      - job_name: 'machine-functional-testing'
        static_configs:
          - targets: ['machine-functionaltesting-svc:8080']

      - job_name: 'temporal-frontend'
        static_configs:
          - targets: ['temporal-svc:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: xts-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: xts-system
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
