apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: xts-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.25.2
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_SEEDS
              value: "postgresql-svc"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-svc
  namespace: xts-system
spec:
  selector:
    app: temporal-server
  ports:
    - port: 7233
      targetPort: 7233
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: xts-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:2.31.2
          ports:
            - containerPort: 8080
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal-svc:7233"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui-svc
  namespace: xts-system
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
